# This is a basic workflow to help you get started with Actions
name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# All the environment variables are defined here
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  MCMPDEMO_DOCKER: ${{ secrets.MCMPDEMO_DOCKER }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker Images
        env:
          JPETSTOREWEB: ${{env.MCMPDEMO_DOCKER}}/jpetstoreweb:${{env.BUILD_NUMBER}}
          JPETSTOREDB: ${{env.MCMPDEMO_DOCKER}}/jpetstoredb:latest
        run: |
          echo "Building docker images..."
          docker build -t ${{env.JPETSTOREWEB}} ./jpetstore
          docker build -t ${{env.JPETSTOREDB}} .
          docker push ${{env.JPETSTOREWEB}}
          docker push ${{env.JPETSTOREDB}}
