# This is a basic workflow to help you get started with Actions
name: CI/CD Pipeline

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# All the environment variables are defined here
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  HELM_PATH: './helm/modernpets/'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Build"
  build:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.build_number.outputs.build_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Getting a short sha and the timestamp
      - name: Setting Github Short SHA & TIMESTAMP
        run: |
          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
          echo "TIMESTAMP=`date -u +%Y%m%d%H%M%S`" >> $GITHUB_ENV

      # Action for get e build number of the pipeline
      - name: Generate build number
        id: build_number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}

      # Action used to log in into Dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      # Building the image and pushing both as a latest image
      - name: Build Docker Images
        env:
          JPETSTOREWEB: ${{env.DOCKER_USERNAME}}/jpetstoreweb
          JPETSTOREDB: ${{env.DOCKER_USERNAME}}/jpetstoredb
          BUILD_TAG: ${{env.BUILD_NUMBER}}-${{github.ref_name}}-${{env.SHORT_SHA}}-${{env.TIMESTAMP}}
        run: |
          echo "Building docker images..."
          docker build -t ${{env.JPETSTOREWEB}}:${{env.BUILD_TAG}} -t ${{env.JPETSTOREWEB}}:latest ./jpetstore
          docker build -t ${{env.JPETSTOREDB}}:${{env.BUILD_TAG}} -t ${{env.JPETSTOREDB}}:latest .
          docker push ${{env.JPETSTOREWEB}}:${{env.BUILD_TAG}}
          docker push ${{env.JPETSTOREWEB}}:latest
          docker push ${{env.JPETSTOREDB}}:${{env.BUILD_TAG}}
          docker push ${{env.JPETSTOREDB}}:latest

  # Job used for deploy app to AKS
  deploy:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Getting the build number for previous job
      - name: Getting build number from above job
        run: echo ${{needs.build.outputs.build_number}}

      # Configuring Java version to run test
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Action used to log in into Dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      # Login into Azure
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Set the kubectl environment
      - name: Setting up Kubectl usage
        uses: azure/setup-kubectl@v2.0

      # Set the target AKS cluster
      - name: Setting up Azure AKS context
        uses: azure/aks-set-context@v2.0
        with:
          resource-group: ${{secrets.AZURE_RESOURCE_GROUP}}
          cluster-name: ${{secrets.AZURE_CLUSTER_NAME}}

      # - name: Setting up helm environment
      #   uses: azure/k8s-bake@v2
      #   id: bake
      #   with:
      #     renderEngine: 'helm'
      #     helmChart: ${{env.HELM_PATH}}
      #     overrideFiles: ${{env.HELM_PATH}}values.yaml
      #     overrides: |
      #       image.repository:${{env.DOCKER_USERNAME}}/
      #       image.tag:${{needs.build.outputs.build_number}}
      #       mysql.url:
      #       isDBAAS:True
      #       isLB:False
      #     helm-version: 'latest'

      # Running the java test with ant command
      - name: Testing jpetstore application
        run: |
          cd jpetstore
          ant runtest

      # Deploying application into AKS
      - name: Deploying AKS
        env:
          WORKDIR: /home/runner/work/jpetstore-kubernetes
          NAMESPACE: 'jpetstore'
        run: |
          helm version
          kubectl delete job jpetstoredb --ignore-not-found -n ${{env.NAMESPACE}}
          helm package --destination ${{env.WORKDIR}}/modernpets ./helm/modernpets
          helm upgrade --install --wait --set image.repository=${{env.DOCKER_USERNAME}} --set image.tag='latest' --set mysql.url=${{secrets.MYSQL_URL}} --set mysql.username=${{secrets.MYSQL_USER}} --set mysql.password=${{secrets.MYSQL_PASSWORD}} --set isDBAAS=True --set isLB=False --set httpHost=${{secrets.PETSTORE_HOST}} --namespace=${{env.NAMESPACE}} --create-namespace ${{env.NAMESPACE}} ${{env.WORKDIR}}/modernpets/modernpets-0.1.5.tgz
          echo "app=`$(kubectl get  ingress -n ${{env.NAMESPACE}} | base64 | tr -d '\r')`" >> GITHUB_ENV
          echo "app_decoded=`$(kubectl get  ingress -n ${{env.NAMESPACE}} | tr -d '\r')`" >> GITHUB_ENV
          echo app running at ${{env.app_decoded}}
          chmod +x result.sh
          ./result.sh ${app}
