# This is a basic workflow to help you get started with Actions
name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# All the environment variables are defined here
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  MCMPDEMO_DOCKER: ${{ secrets.MCMPDEMO_DOCKER }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}
      - name: Build
        run: |
          echo "This is a test for build"
          echo "Build number is $BUILD_NUMBER"
          echo "TODAY=$(date -I)" >> $GITHUB_ENV
      # echo "JPETSTOREWEB=$MCMPDEMO_DOCKER/jpetstoreweb:$BUILD_NUMBER" >> $GITHUB_ENV
      - name: Get env
        ruin: echo "$TODAY"
